name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Create Issue
      uses: actions/github-script@v5
      with:
        script: |
          const issue = await github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Passing Data',
            body: 'param1=value1\nparam2=value2', // Your data here
          });
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
