name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow_2:
    runs-on: ubuntu-latest

    env:
      BUILD_ID: 12345
      SUITE_NAME: MySuite
      TAG_NAME: v1.0.0

    steps:
    - name: Dispatch Workflow 2
      uses: peter-evans/repository-dispatch@v1
      with:
        workflow: Workflow 2
        token: ${{ secrets.GITHUB_TOKEN }}
