name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  create_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Create Issue
      run: |
        echo "Creating issue..."
        issue_data="{\"title\":\"Passing Data\",\"body\":\"param1=value1\\nparam2=value2\"}"  # Replace with your data
        response=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "$issue_data" "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues")
        echo "Response: $response"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
