name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  trigger_workflow_2:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Workflow 2
      run: |
        echo "::set-env name=BUILD_ID::12345"
        echo "::set-env name=SUITE_NAME::MySuite"
        echo "::set-env name=TAG_NAME::v1.0.0"
        echo "Variables set for Workflow 2."
      shell: bash

    - name: Dispatch Workflow 2
      uses: peter-evans/repository-dispatch@v1
      with:
        workflow: Workflow 2
        token: ${{ secrets.GITHUB_TOKEN }}
