name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  read_variables:
    runs-on: ubuntu-latest

    steps:
    - name: Download Variables
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: ../

    - name: Read Variables
      run: |
        source variables.txt  # Load the variables
        echo "Build ID: $build_id"
        echo "Suite Name: $suite_name"
        echo "Tag Name: $tag_name"
