name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create artifact file
      run: |
        echo "param1=value1" >> params.txt
        echo "param2=value2" >> params.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact  # Make sure the artifact name here matches the download step in Workflow 2
        path: params.txt
