name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  read_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Read Issue Data
      run: |
        commit_message=$(git log --format=%B -n 1 ${{ github.event.workflow_run.head_commit.id }})
        issue_number=$(echo "$commit_message" | grep -oP '#\d+' | sed 's/#//')
        if [ -n "$issue_number" ]; then
          echo "Found issue number: $issue_number"
          # Now you can use $issue_number to fetch the issue comments
        else
          echo "Issue number not found in commit message."
        fi
