name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  read_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Extract Issue Number
      id: extract-issue-number
      run: echo "::set-output name=issue_number::$(echo ${{ github.event.workflow_run.head_commit.message }} | grep -oP '#\\d+' | grep -oP '\\d+')"

    - name: Read Issue Data
      uses: actions/github-script@v5
      with:
        script: |
          const issueNumber = ${{ steps.extract-issue-number.outputs.issue_number }};
          const response = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: parseInt(issueNumber),
          });
          const params = response.data.map(comment => comment.body).join('\n');
          console.log(params);
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
