name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  read_variables:
    runs-on: ubuntu-latest

    steps:
    - name: Read Environment Variables
      run: |
        echo "Build ID: $BUILD_ID"
        echo "Suite Name: $SUITE_NAME"
        echo "Tag Name: $TAG_NAME"
