name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  use-data:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get data
        run: |
          echo ${{ needs.build.outputs.var1 }}
          echo ${{ needs.build.outputs.var2 }}
          echo ${{ needs.build.outputs.var3 }}
