name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  set_env_file:
    runs-on: ubuntu-latest

    steps:
    - name: Create Environment File
      run: |
        echo "BUILD_ID=12345" > env_file.txt
        echo "SUITE_NAME=MySuite" >> env_file.txt
        echo "TAG_NAME=v1.0.0" >> env_file.txt

    - name: Upload Environment File
      uses: actions/upload-artifact@v2
      with:
        name: env-file
        path: env_file.txt
