name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set outputs
        run: |
          echo "VAR1=my-var1" | tee outputs.var1
          echo "VAR2=my-var2" | tee outputs.var2
          echo "VAR3=my-var3" | tee outputs.var3
