name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: .
    
    - name: Read parameters from artifact
      run: |
        param1=$(cat params.txt | grep "param1" | cut -d'=' -f2)
        param2=$(cat params.txt | grep "param2" | cut -d'=' -f2)
        echo "Parameter 1: $param1"
        echo "Parameter 2: $param2"
