name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create artifact file
      run: |
        echo "::set-output name=param1::testValue1" >> params.txt
        echo "::set-output name=param2::testValue2" >> params.txt
        echo "::set-output name=artifact_path::params.txt"
      id: params

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: workflow1-artifact
        path: ${{ steps.params.outputs.artifact_path }}
