name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
      build:
        runs-on: ubuntu-latest
        
        steps:
          - name: Download Artifact
            uses: actions/download-artifact@v2
            with:
              name: my-artifact
              path: ${{ runner.workspace }}

          - name: Read Variable
            id: read-variable
            run: echo "The value of MY_VARIABLE is ${{ env.MY_VARIABLE }}"
