name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  read_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Read Issue Data
      uses: actions/github-script@v5
      with:
        script: |
          const response = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.payload.workflow_run.payload.pull_requests[0].number, // Extract the issue number from the workflow run
          });
          const params = response.data.map(comment => comment.body).join('\n');
          console.log(params);
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
