name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  set_variables:
    runs-on: ubuntu-latest

    steps:
    - name: Set Variables
      run: |
        echo "build_id=12345" > variables.txt
        echo "suite_name=MySuite" >> variables.txt
        echo "tag_name=v1.0.0" >> variables.txt

    - name: Upload Variables 
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: variables.txt
