name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Download artifact from Workflow 1
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        workflow: "Workflow 1"  # Specify the name of Workflow 1 here
    
    - name: Display Parameters
      run: |
        cat params.txt  # Display the content of the artifact file
    
    - name: Read parameters from artifact
      run: |
        param1=$(cat params.txt | grep "param1" | cut -d'=' -f2)
        param2=$(cat params.txt | grep "param2" | cut -d'=' -f2)
        echo "Parameter 1: $param1"
        echo "Parameter 2: $param2"
