name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Display Parameters
      run: |
        echo "Parameter 1: ${{ github.event.workflow_run.event.inputs.param1 }}"
        echo "Parameter 2: ${{ github.event.workflow_run.event.inputs.param2 }}"
