name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Variable
        id: set-variable
        run: echo "MY_VARIABLE=Hello from Workflow A" >> $GITHUB_ENV

      - name: Create Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ${{ runner.workspace }}
