name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  read_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Read Issue Data
      env:
        ISSUE_NUMBER: ${{ github.event.workflow_run.head_commit.message | grep -oP '#\\d+' | grep -oP '\\d+' }}
      run: |
        if [ -n "$ISSUE_NUMBER" ]; then
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER/comments"
        else
          echo "Issue number not found in commit message."
        fi
