name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  read_env_file:
    runs-on: ubuntu-latest

    steps:
    - name: Download Environment File
      uses: actions/download-artifact@v2
      with:
        name: env-file
        path: .

    - name: Read Environment Variables
      run: |
        source env_file.txt
        echo "Build ID: $BUILD_ID"
        echo "Suite Name: $SUITE_NAME"
        echo "Tag Name: $TAG_NAME"
