name: Workflow 1

on:
  push:
    branches:
      - main

jobs:
  set_variables:
    runs-on: ubuntu-latest

    env:
      BUILD_ID: 12345
      SUITE_NAME: MySuite
      TAG_NAME: v1.0.0

    steps:
    - name: Trigger Workflow 2
      uses: actions/workflow-dispatch@v2
      with:
        workflow: Workflow 2
        inputs: |
          build_id=$BUILD_ID
          suite_name=$SUITE_NAME
          tag_name=$TAG_NAME
