name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  read_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Read Issue Data
      uses: actions/github-script@v5
      with:
        script: |
          const issueNumber = github.context.payload.workflow_run.head_commit.message.match(/#(\d+)/);
          if (issueNumber) {
            const response = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt(issueNumber[1]), // Extract the issue number from the commit message
            });
            const params = response.data.map(comment => comment.body).join('\n');
            console.log(params);
          } else {
            console.log('Issue number not found in commit message.');
          }
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
